use neonet_core::NodeType;
use serde::{Deserialize, Serialize};

use crate::bytes64::serde_bytes64;

// ── Handshake messages (4-message exchange) ──────────────────────────
//
//  A ── HelloInit ──► B       (eph_pubkey_a)
//  A ◄── HelloResp ── B       (eph_pubkey_b + encrypted identity_b)
//  A ── Finish ─────► B       (encrypted identity_a + session_id)
//  A ◄── Ack ──────── B       (session_id echo)

/// First message from initiator (A).
///
/// Contains only the ephemeral X25519 public key and padding.
/// No identity is revealed at this stage.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HelloInit {
    /// Protocol version (currently 1).
    pub version: u8,
    /// Ephemeral X25519 public key of A.
    pub eph_pubkey: [u8; 32],
    /// Random padding (multiple of 256 bytes total).
    pub padding: Vec<u8>,
}

/// Response from responder (B).
///
/// Contains B's ephemeral key and encrypted identity. After receiving
/// this, A can derive the shared secret and session keys via HKDF.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HelloResp {
    /// Ephemeral X25519 public key of B.
    pub eph_pubkey: [u8; 32],
    /// `IdentityPayload` of B, encrypted with ChaCha20-Poly1305.
    pub identity_enc: Vec<u8>,
    /// Random padding.
    pub padding: Vec<u8>,
}

/// Third message: A reveals identity to B.
///
/// Contains the session ID chosen by A and A's encrypted identity.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Finish {
    /// Random session identifier (generated by A).
    pub session_id: [u8; 16],
    /// `IdentityPayload` of A, encrypted with ChaCha20-Poly1305.
    pub identity_enc: Vec<u8>,
    /// Random padding.
    pub padding: Vec<u8>,
}

/// Final acknowledgement from B.
///
/// Echoes the session ID to confirm both sides agree on the session.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Ack {
    /// Echo of the `session_id` received in `Finish`.
    pub session_id: [u8; 16],
    /// Random padding.
    pub padding: Vec<u8>,
}

// ── Identity payload (encrypted inside HelloResp & Finish) ──────────

/// Identity proof transmitted inside the handshake, always encrypted.
///
/// An observer never sees public keys in the clear during the handshake.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IdentityPayload {
    /// Long-term Ed25519 public key.
    pub pubkey: [u8; 32],
    /// Ed25519 signature over `session_id || eph_pubkey`.
    #[serde(with = "serde_bytes64")]
    pub sig: [u8; 64],
    /// Node role in the network.
    pub node_type: NodeType,
    /// Bitfield of supported features.
    pub features: u32,
}

// ── HKDF parameters ─────────────────────────────────────────────────

/// Fixed salt used for session key derivation via HKDF-SHA256.
pub const HKDF_SALT: &[u8] = b"neonet-v1-session";

/// Number of output bytes from HKDF (2 x 32-byte keys).
pub const HKDF_OUTPUT_LEN: usize = 64;

// ── Padding helper ──────────────────────────────────────────────────

/// Pad length to the next multiple of 256 bytes.
pub const PADDING_BLOCK: usize = 256;

pub fn padding_len(content_len: usize) -> usize {
    let padded = (content_len + PADDING_BLOCK - 1) / PADDING_BLOCK * PADDING_BLOCK;
    padded - content_len
}
